name: Python

on: [push]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Advent of Code
        run: for f in $PWD/days/*.py; do python $f && printf "\n\n\n\n\n"; done
